"""add_plans_table_and_plan_id_to_subscriptions

Revision ID: 4775b966c694
Revises: add_user_settings_fields
Create Date: 2025-08-01 22:27:03.962968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4775b966c694'
down_revision: Union[str, Sequence[str], None] = 'add_user_settings_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('channels_limit', sa.Integer(), nullable=False),
    sa.Column('posts_limit', sa.Integer(), nullable=False),
    sa.Column('manual_posts_limit', sa.Integer(), nullable=False),
    sa.Column('ai_priority', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('usage_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('posts_used', sa.Integer(), nullable=True),
    sa.Column('manual_posts_used', sa.Integer(), nullable=True),
    sa.Column('channels_connected', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_stats_id'), 'usage_stats', ['id'], unique=False)
    op.create_index(op.f('ix_usage_stats_subscription_id'), 'usage_stats', ['subscription_id'], unique=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('subscriptions', sa.Column('plan_id', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscriptions', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('type', postgresql.ENUM('basic', 'premium', 'enterprise', name='subscription_type'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'auto_renew')
    op.drop_column('subscriptions', 'plan_id')
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_usage_stats_subscription_id'), table_name='usage_stats')
    op.drop_index(op.f('ix_usage_stats_id'), table_name='usage_stats')
    op.drop_table('usage_stats')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
