"""add_free_posts_limit_field

Revision ID: a7be12f9b5d4
Revises: 4775b966c694
Create Date: 2025-08-02 22:21:49.441575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7be12f9b5d4'
down_revision: Union[str, Sequence[str], None] = '4775b966c694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('free_posts_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'free_posts_limit')
    # ### end Alembic commands ###
