"""add user settings fields

Revision ID: add_user_settings_fields
Revises: a1b2c3d4e5f6
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_user_settings_fields'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notify_new_posts', sa.Boolean(), nullable=True, default=True))
    op.add_column('users', sa.Column('notify_scheduled', sa.Boolean(), nullable=True, default=True))
    op.add_column('users', sa.Column('notify_errors', sa.Boolean(), nullable=True, default=True))
    op.add_column('users', sa.Column('notify_payments', sa.Boolean(), nullable=True, default=True))
    op.add_column('users', sa.Column('default_language', sa.String(length=2), nullable=True, default='ru'))
    op.add_column('users', sa.Column('default_style', sa.String(length=20), nullable=True, default='friendly'))
    op.add_column('users', sa.Column('default_length', sa.String(length=20), nullable=True, default='medium'))
    op.add_column('users', sa.Column('default_moderation', sa.Boolean(), nullable=True, default=False))
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=True, default=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=True, default=0))
    op.add_column('users', sa.Column('theme', sa.String(length=20), nullable=True, default='light'))
    op.add_column('users', sa.Column('compact_mode', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'compact_mode')
    op.drop_column('users', 'theme')
    op.drop_column('users', 'login_count')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('users', 'default_moderation')
    op.drop_column('users', 'default_length')
    op.drop_column('users', 'default_style')
    op.drop_column('users', 'default_language')
    op.drop_column('users', 'notify_payments')
    op.drop_column('users', 'notify_errors')
    op.drop_column('users', 'notify_scheduled')
    op.drop_column('users', 'notify_new_posts')
    # ### end Alembic commands ### 